print(f"---------------------------------------")
print(f"|        Roberto                      |")
print(f"|                                     |")
print(f"|        5786                         |")
print(f"|                                     |")
print(f"|        UNIFEI                       |")
print(f"---------------------------------------")
